name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: merger-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install -r requirements/dev.txt

      - name: Run tests
        run: pytest
        env:
          ENV: ${{ vars.ENV }}
          RATE_LIMIT: ${{ vars.RATE_LIMIT }}
          CORS_ALLOWED_ORIGINS: ${{ vars.CORS_ALLOWED_ORIGINS }}
  
  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v4
        with:
          registry: pdfmergercr.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./merger-api
          push: true
          tags: pdfmergercr.azurecr.io/pdf-merger-api:latest
