name: Deploy
run-name: Deploy for ${{ github.repository }}/merger-api.

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build_and_push:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    outputs:
      image_tag: ${{ steps.meta.outputs.sha_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generate image tag
        id: meta
        run: |
          SHA_TAG="sha-${{ github.event.workflow_run.head_sha }}"
          echo "sha_tag=${SHA_TAG}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ./merger-api
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pdf-merger:latest
            ghcr.io/${{ github.repository_owner }}/pdf-merger:sha-${{ github.event.workflow_run.head_sha }}

